image: thangpham310/java8-mvn-nodejs-npm:latest

pipelines:
  default:
    - step:
        caches:
          - maven
          - front-end
        script:
          - mvn clean install

definitions:
  caches:
    front-end: /opt/atlassian/pipelines/agent/build/src/webui
