server:
  port: 9000

jira:
  domain: https://jira.rsi.lexisnexis.com
  fetch-story-url: /rest/api/2/search
  jql-query: project = MAS AND issuetype in (Bug, Story, "Bug Sub-Task") AND Sprint = %s
  token: UGhhbVRoMDFAcmlzazpIQHJkd29yaw==

git:
  domain: http://plgithub01.hmsonline.com
  fetch-pull-request-url: /api/v3/repos/kms-lnhc/%s/pulls
  token: d48ee5883255d4bcd6668424237c53cd672708dc

checkprofile:
  domain: http://ci01.dolphin.lexisnexisrisk.com
  fetch-url: /cgi-bin/checkprofile.py
